### ISSUE TITLE
possible typo?

### ISSUE THREAD

**Issue by rolanvc** [surfertas/deep_learning#1]
Hi sufertas. First of all, I'd like to thank you fot this. It really helped. Ithink what you did here is awesome.

Just a question though:
inside class RNNModel(object):, inside __init__():
you have **self._p_drop= p_dropout** 
then later **self._dropout = None**

then, inside def _model(self, w, b):, inside  def __cell():
you have  **return tf.contrib.rnn.DropoutWrapper(rnn_cell, output_keep_prob=self._dropout)**

I'm wondering if this was intentional( self_dropout is None, or did you mean to put self._p_drop?

Thank you again!

**Comment by rolanvc** [comment]
Never mind the issue i opened. I realized that self._dropout is set by the graph during training time.

**Comment by surfertas** [comment]
Sorry I missed this.
